### ISSUE TITLE
PHP 7.0 - E_STRICT

### ISSUE THREAD

**Issue by davidvandertuijn** [maximivanov/php-error-reporting-calculator#3]
In PHP7 the E_STRICT have no meaning, can you add PHP 7.0 and exclude E_STRICT ?

https://wiki.php.net/rfc/reclassify_e_strict

**Comment by maximivanov** [comment]
Thanks @davidvandertuijn! I haven't used PHP for a long time now and I was unaware of the change.
It seems like this tool still gets occasional visitors so I've updated it.

I decided to not exclude E_STRICT from the list since technically it's still a part of E_ALL:

```bash
❯ docker run -it --rm php:7-alpine php -r "var_dump(E_ALL);"
int(32767)
```

It may be confusing if someone tries to deconstruct the `32767` and there's no constant for the E_STRICT.

I've added a link to the page you posted above though.

Cheers!

**Comment by davidvandertuijn** [comment]
Awesome!
